### ISSUE TITLE
error fetching identities: invalid format and could not add identity id_rsa invalid format

### ISSUE THREAD

**Issue by sheam** [dahlbyk/posh-sshell#27]
I have my .ssh keys in `C:\Users\myname\.ssh`. These keys work with git-bash, as well as on my Linux machine.
In my powershell profile is:
```
Import-Module posh-git

Import-Module posh-sshell
Start-SshAgent -Quiet
```

But Start-SshAgent keeps giving me the following output:
```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

error fetching identities: invalid format
Enter passphrase for C:\Users\sheam/.ssh/id_rsa:
Could not add identity "C:\Users\sheam/.ssh/id_rsa": invalid format
Loading personal and system profiles took 10119ms.
~\Code\BrewNinja [5124-direct-invoicing-ux-feature-enable ≡]>
```

### System Details

- posh-sshell version/path: 0.3.1  ~\Documents\PowerShell\Modules\posh-sshell\0.3.1
- PowerShell version: 7.0.3
- OS: Microsoft Windows NT 10.0.19041.0

**Comment by JeremySkinner** [comment]
Hi, it looks like that message is coming from ssh-add.exe directly and isn’t related to posh-sshell. 

I would suggest you start troubleshooting by running `ssh-add` manually. Does the same message come up? If so then this isn’t related to posh-shell and is likely an incompatibility between your key format and the version of OpenSSH that’s in your PATH. I’m assuming it’s the windows-native version of openssh you’re using?

**Comment by sheam** [comment]
Thanks Jeremy. Yeah, win native. I have no idea what the issue with my key is. Definitely not a posh-sshell issue I guess. Does win native use a different formant for id_rsa?

**Comment by sheam** [comment]
If I have to create a new key to use with native open ssh, is there a way I can tell Posh-Sshell to use a specific private key?

**Comment by JeremySkinner** [comment]
> Does win native use a different formant for id_rsa?

Older versions were limited to only 1 format, but I believe this was fixed in modern releases https://github.com/PowerShell/Win32-OpenSSH/issues/973. Best to ask on their official repo if you're having problems with it still. 

>  is there a way I can tell Posh-Sshell to use a specific private key?

To be honest there's no need to use posh-sshell if you're using the windows native ssh agent, as it uses a windows service. Make sure that the OpenSSH Agent Service is started and set to automatic, call `ssh-add.exe` once (specifying your keyfile) and then the agent will be automatically started and add your key every time you reboot. There's no need to manage the agent with `Start-SshAgent` in your profile, as windows will do it for you. The agent management functions in posh-sshell are really only useful for other ssh agents which don't auto-start (pageant, msysgit's ssh etc).
